title = "Purity"
base_url = "https://blog.sombia.com"

[markdown]
highlight_code = true

[extra]
purity_author = "Rob Wagner"
purity_email = "rob@sombia.com"
purity_github = "robertwayne"
purity_tagline = "A seriously minimalistic blog theme for Zola."
