name = "Purity"
description = "A minimalistic, dark blog theme."
license = "MIT or Apache-2.0"
homepage = "https://github.com/robertwayne/purity"
min_version = "0.16"

[author]
name = "Rob Wagner"
homepage = "https://blog.sombia.com"

[extra]
purity_author = ""
purity_email = ""
purity_github = ""
purity_subtitle = ""
